### ISSUE TITLE
Trees cannot be loaded after creation of new account without trees

### ISSUE THREAD

**Issue by fbennets** [open-decision/open-decision#193]
After creating a new account, loading the dashboard errors out. See console log below.

This only happens instantly after login or registration, when being signed and reloading the dashboard, everything works fine.

This also happens at main branch.

<img width="994" alt="Bildschirmfoto 2022-07-04 um 11 09 05" src="https://user-images.githubusercontent.com/35722762/177122536-bc490e6f-3ce1-448b-83d4-a2ddeac6394a.png">
 
```instrument.js:107 TypeError: Cannot read properties of undefined (reading 'getCollection')
    at useTreesQuery.ts:11:29
    at s (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at forEach.e.<computed> [as next] (runtime.js:97:21)
    at r (_async_to_generator.mjs:3:20)
    at a (_async_to_generator.mjs:25:9)
    at _async_to_generator.mjs:32:7
    at new Promise (<anonymous>)
    at Object.queryFn (_async_to_generator.mjs:21:12)
    at Object.fetchFn [as fn] (query.js:298:29)
    at u (retryer.js:95:31)
    at retryer.js:149:11
(anonymous) @ instrument.js:107
instrument.js:107 TypeError: Cannot read properties of undefined (reading 'getCollection')
    at useTreesQuery.ts:11:29
    at s (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at forEach.e.<computed> [as next] (runtime.js:97:21)
    at r (_async_to_generator.mjs:3:20)
    at a (_async_to_generator.mjs:25:9)
    at _async_to_generator.mjs:32:7
    at new Promise (<anonymous>)
    at Object.queryFn (_async_to_generator.mjs:21:12)
    at Object.fetchFn [as fn] (query.js:298:29)
    at u (retryer.js:95:31)
    at retryer.js:149:11
(anonymous) @ instrument.js:107```

**Comment by PhilGarb** [comment]
This should be fixed by #199
